# Generated by Django 2.1.7 on 2019-03-11 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('photo', models.CharField(max_length=1000)),
                ('alive', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('portrayed_by', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100)),
                ('banner', models.CharField(max_length=500)),
                ('current_ruler', models.CharField(max_length=100)),
                ('slogan', models.CharField(max_length=200)),
                ('sigil', models.CharField(max_length=200)),
                ('founder', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=4000)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wiki.House'),
        ),
    ]
